### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by MrMaksimize** [cityofsandiego/datasd#44]
Readme needs clearer installation instructions.

**Comment by 47ronin** [comment]
I'll try to take care of that in my next PR tonight. 😁

**Comment by MrMaksimize** [comment]
Sweet!

**Comment by 47ronin** [comment]
💡 There are some opportunities for additional info in the README. Wanted to run these by you first, but they'll need copy that someone has to write:

- Introduction section that states the purpose of the project, some background
- Possibly a screenshot
- Near the end, maybe a resources type section which has contact info for your team, etc.
- Because the data is merged into this statically, maybe it would be a good idea to exmplain and emphasize the CONTRIBUTING.md

Cheers!

**Comment by MrMaksimize** [comment]
Let's do it!  If you wanna open up a new issue / PR, we can work on it together :)  Once we're happy with the readme, we can see if we can re-use similar readme structure for the rest of SD's open source projects :)
